@echo off & setlocal enabledelayedexpansion


for /f %%a in ('cmd /k prompt $e^<nul') do (set "esc=%%a")
reg add "HKCU\Console" /v VirtualTerminalLevel /t REG_DWORD /d 1 /f >nul 2>&1

echo %esc%[2J%esc%[1;1H
echo %esc%[93m========================================%esc%[0m
echo %esc%[93m     画面環境検出システム ver.0%esc%[0m
echo %esc%[93m========================================%esc%[0m
echo.

:: 0. フルスクリーンモードの設定

echo %esc%[96m[0] フルスクリーンモードを有効化中...%esc%[0m
Tools\cmdwiz.exe fullscreen 1

echo %esc%[92m   [OK] フルスクリーンモードが有効化されました%esc%[0m


:: 1. 画面解像度の取得

echo %esc%[96m[1] 画面解像度の検出中... %esc%[0m

:: PowerShellで画面解像度を取得

for /f "usebackq tokens=*" %%a in (`powershell -NoProfile -Command "Add-Type -AssemblyName System.Windows.Forms; $s=[System.Windows.Forms.Screen]::PrimaryScreen.Bounds; Write-Output $($s.Width); Write-Output $($s.Height)"`) do (
    if not defined screen_width (
        set screen_width=%%a
    ) else (
        set screen_height=%%a
    )
)

echo %esc%[92m   [OK] 画面解像度: %screen_width% x %screen_height%%esc%[0m

:: 2. コンソールウィンドウサイズの取得

echo %esc%[96m[2] コンソールウィンドウサイズの検出中...%esc%[0m

for /f "tokens=*" %%a in ('powershell -Command "$host.UI.RawUI.WindowSize.Width"') do set console_width=%%a
for /f "tokens=*" %%a in ('powershell -Command "$host.UI.RawUI.WindowSize.Height"') do set console_height=%%a

echo %esc%[92m   [OK] コンソールサイズ: %console_width% x %console_height%%esc%[0m


:: 3. 文字サイズの推定

echo %esc%[96m[3] 文字サイズの推定中...%esc%[0m
set /a char_width_est=!screen_width!/!console_width!
set /a char_height_est=!screen_height!/!console_height!

echo %esc%[92m   [OK] 推定文字サイズ: %char_width_est% x %char_height_est% ピクセル%esc%[0m

:: 4. 環境ファイルの生成

echo %esc%[96m[4] 環境設定ファイルの生成中...%esc%[0m
call :Generate_Environment_Config

echo %esc%[92m   [OK] 環境設定ファイル生成完了%esc%[0m

:: 5. 互換性テスト

echo %esc%[96m[5] 表示互換性テストの実行%esc%[0m
timeout /t 3 >nul
echo %esc%[92m   [OK] 互換性テスト完了%esc%[0m
:: call :Run_Compatibility_Test
echo.
echo %esc%[93m========================================%esc%[0m
echo %esc%[93m     検出完了%esc%[0m
echo %esc%[93m========================================%esc%[0m
echo.
echo %esc%[97m何かキーを押してください...%esc%[0m
pause >nul
Tools\cmdwiz.exe fullscreen 0
exit /b 0











:Generate_Environment_Config
    set config_file=%cd%\Systems\Environment\screen_config.env
    
    echo REM Generated by ScreenDetector.bat > "%config_file%"
    echo REM Date: %date% %time% >> "%config_file%"
    echo. >> "%config_file%"
    echo :: 画面解像度 >> "%config_file%"
    echo set SCREEN_WIDTH=%screen_width% >> "%config_file%"
    echo set SCREEN_HEIGHT=%screen_height% >> "%config_file%"
    echo. >> "%config_file%"
    echo :: コンソールサイズ >> "%config_file%"
    echo set CONSOLE_WIDTH=%console_width% >> "%config_file%"
    echo set CONSOLE_HEIGHT=%console_height% >> "%config_file%"
    echo. >> "%config_file%"
    echo :: 推定文字サイズ >> "%config_file%"
    echo set CHAR_WIDTH_EST=%char_width_est% >> "%config_file%"
    echo set CHAR_HEIGHT_EST=%char_height_est% >> "%config_file%"
    echo. >> "%config_file%"
    echo :: 環境分類 >> "%config_file%"
    


    if %screen_width% LEQ 1366 (
        echo set SCREEN_CLASS=SMALL >> "%config_file%"
        echo set UI_SCALE=0.8 >> "%config_file%"
    ) else if %screen_width% LEQ 1920 (
        echo set SCREEN_CLASS=MEDIUM >> "%config_file%"
        echo set UI_SCALE=1.0 >> "%config_file%"
    ) else (
        echo set SCREEN_CLASS=LARGE >> "%config_file%"
        echo set UI_SCALE=1.2 >> "%config_file%"
    )
    
    exit /b 0











:Run_Compatibility_Test
    echo %esc%[2J%esc%[1;1H
    echo %esc%[93m=== 表示互換性テスト ===%esc%[0m
    echo.
    
    :: 四隅の座標テスト

    echo %esc%[1;1H%esc%[91m[1,1]%esc%[0m
    echo %esc%[1;%console_width%H%esc%[91m[1,%console_width%]%esc%[0m
    echo %esc%[%console_height%;1H%esc%[91m[%console_height%,1]%esc%[0m
    echo %esc%[%console_height%;%console_width%H%esc%[91m[%console_height%,%console_width%]%esc%[0m
    
    :: 中央の座標テスト

    set /a center_row=!console_height!/2
    set /a center_col=!console_width!/2
    echo %esc%[!center_row!;!center_col!H%esc%[92m[CENTER]%esc%[0m
    
    :: ゲームUIの想定位置テスト

    set /a game_menu_row=!console_height!/2-5
    set /a game_menu_col=!console_width!/2-10
    echo %esc%[!game_menu_row!;!game_menu_col!H%esc%[96m+------------------+%esc%[0m
    echo %esc%[!game_menu_row!;!game_menu_col!H%esc%[96m^|   GAME MENU TEST ^|%esc%[0m
    echo %esc%[!game_menu_row!;!game_menu_col!H%esc%[96m+------------------+%esc%[0m
    
    echo %esc%[!console_height!;1H%esc%[93m四隅と中央の座標が正しく表示されているか確認してください%esc%[0m
    
    timeout /t 30 >nul
    exit /b 0