@echo off
setlocal EnableExtensions
rem -----------------------------------------------------------------------------
rem SettingPath.bat  (RCSU/RC BE)
rem Role:
rem   Resolve all directory variables from root and export to parent scope
rem   Optionally add Tools to your PATH without duplicates
rem RC:
rem   FLOW/SYS/OTHER/000 : 1-06-90-000 : OK
rem -----------------------------------------------------------------------------

call "%RCSU%" -trace INFO SettingPath "Start setting directory path variable"

rem ─── If PROJECT_ROOT exists, use it. If not, complete it yourself. ──
if defined PROJECT_ROOT (
   set "root_dir=%PROJECT_ROOT%"
) else (
   for %%I in ("%~dp0\..\..\..") do set "root_dir=%%~fI\"
)

rem ---Added: If SAVE_MODE is undefined, load profile.env and automate ---
if not defined SAVE_MODE (
  set "_cfg_guess=%root_dir%\Config"
  if not defined CFG_DIR set "CFG_DIR=%_cfg_guess%"
  if exist "%CFG_DIR%\profile.env" (
    call "%PROJECT_ROOT%\Src\Systems\Environment\LoadEnv.bat" "%CFG_DIR%\profile.env" >nul
    set "RC=%errorlevel%"
    if not "%RC%"=="%RC_OK%" (
      rem Since it is an option read, it will not be dropped even if it fails (log only)
      call "%RCSU%" -trace WARN SettingPath "LoadEnv optional rc=%RC% file=%CFG_DIR%\profile.env"
    )
  )
)



::===== Under Assets ====================================================
set "assets_dir=%root_dir%\Assets"
set "assets_docs_dir=%assets_dir%\Docs"
set "assets_images_dir=%assets_dir%\Images"
set "assets_sounds_dir=%assets_dir%\Sounds"
   set "assets_sounds_revelation_dir=%assets_sounds_dir%\RevelationOfGod"
   set "assets_sounds_starfall_dir=%assets_sounds_dir%\StarFallHill"
   set "assets_sounds_fx_dir=%assets_sounds_dir%\_SoundEffect"

::===== Under Src =======================================================
set "src_dir=%root_dir%\Src"
set "src_data_dir=%src_dir%\Data"
   set "src_enemydata_dir=%src_data_dir%\EnemyData"
   set "src_itemdata_dir=%src_data_dir%\ItemData"
   set "src_playerdata_dir=%src_data_dir%\PlayerData"
set "src_main_dir=%src_dir%\Main"
set "src_network_dir=%src_dir%\Network"
set "src_stories_dir=%src_dir%\Stories"
   set "src_scenes_dir=%src_stories_dir%\Scenes"
      set "src_scene_newgame_dir=%src_scenes_dir%\00_NewGame"
      set "src_scene_prologue_dir=%src_scenes_dir%\01_Prologue"
      rem (Other scenes are dynamically referenced by %src_scenes_dir%\{ID_Name})
   set "src_textassets_dir=%src_stories_dir%\TextAssets"
      set "src_text_newgame_dir=%src_textassets_dir%\00_NewGame"
      set "src_text_prologue_dir=%src_textassets_dir%\01_Prologue"
      rem (Also dynamically accessible)

set "src_systems_dir=%src_dir%\Systems"
   set "src_audio_dir=%src_systems_dir%\Audio"
   set "src_bootstrap_dir=%src_systems_dir%\Bootstrap"
   set "src_debug_dir=%src_systems_dir%\Debug"
   set "src_display_dir=%src_systems_dir%\Display"
      set "src_display_mod_dir=%src_display_dir%\Modules"
      set "src_display_tpl_dir=%src_display_dir%\Templates"
   set "src_env_dir=%src_systems_dir%\Environment"
   set "src_launcher_dir=%src_systems_dir%\Launcher"
   set "src_savesys_dir=%src_systems_dir%\SaveSys"

::===== Config (active location resolved by SAVE_MODE / CFG_DIR) ========
set "config_root_dir=%root_dir%\Config"

if defined CFG_DIR (
   rem Top priority is given to the location specified by Run.bat etc.
   set "config_active_dir=%CFG_DIR%"
) else (
   if /i "%SAVE_MODE%"=="localappdata" (
      set "config_active_dir=%LOCALAPPDATA%\HedgeHogSoft\AstralDivide\Config"
   ) else if /i "%SAVE_MODE%"=="custom" (
      if defined SAVE_DIR (
         set "config_active_dir=%SAVE_DIR%\_config"
      ) else (
         set "config_active_dir=%config_root_dir%"
      )
   ) else (
      rem default: portable
      set "config_active_dir=%config_root_dir%"
   )
)

set "config_profile_file=%config_active_dir%\profile.env"
set "config_cache_dir=%config_active_dir%\Cache"
set "config_logs_dir=%config_active_dir%\Logs"

rem --- Screen env cache (generated by ScreenEnvironmentDetection.bat) ---
set "screen_cache_dir=%config_cache_dir%\Screen\%COMPUTERNAME%"
set "screen_cfg_file=%screen_cache_dir%\screen_config.env"

::===== Saves (active) ==================================================
if defined SAVE_DIR (
   set "saves_active_dir=%SAVE_DIR%"
) else (
   set "saves_active_dir=%root_dir%\Saves"
)

::===== Test / Tools / [DEV] ===========================================
set "test_dir=%root_dir%\Test"
set "tools_dir=%root_dir%\Tools"
set "dev_dir=%root_dir%\[DEV]"

rem --- Export the variables defined so far to the parent scope -------------------
endlocal & (
  set "esc=%esc%"
  set "root_dir=%root_dir%"
  set "assets_dir=%assets_dir%"
  set "assets_docs_dir=%assets_docs_dir%"
  set "assets_images_dir=%assets_images_dir%"
  set "assets_sounds_dir=%assets_sounds_dir%"
  set "assets_sounds_revelation_dir=%assets_sounds_revelation_dir%"
  set "assets_sounds_starfall_dir=%assets_sounds_starfall_dir%"
  set "assets_sounds_fx_dir=%assets_sounds_fx_dir%"
  set "src_dir=%src_dir%"
  set "src_data_dir=%src_data_dir%"
  set "src_enemydata_dir=%src_enemydata_dir%"
  set "src_itemdata_dir=%src_itemdata_dir%"
  set "src_playerdata_dir=%src_playerdata_dir%"
  set "src_main_dir=%src_main_dir%"
  set "src_network_dir=%src_network_dir%"
  set "src_stories_dir=%src_stories_dir%"
  set "src_scenes_dir=%src_scenes_dir%"
  set "src_scene_newgame_dir=%src_scene_newgame_dir%"
  set "src_scene_prologue_dir=%src_scene_prologue_dir%"
  set "src_textassets_dir=%src_textassets_dir%"
  set "src_text_newgame_dir=%src_text_newgame_dir%"
  set "src_text_prologue_dir=%src_text_prologue_dir%"
  set "src_systems_dir=%src_systems_dir%"
  set "src_audio_dir=%src_audio_dir%"
  set "src_bootstrap_dir=%src_bootstrap_dir%"
  set "src_debug_dir=%src_debug_dir%"
  set "src_display_dir=%src_display_dir%"
  set "src_display_mod_dir=%src_display_mod_dir%"
  set "src_display_tpl_dir=%src_display_tpl_dir%"
  set "src_env_dir=%src_env_dir%"
  set "src_launcher_dir=%src_launcher_dir%"
  set "src_savesys_dir=%src_savesys_dir%"
  set "config_root_dir=%config_root_dir%"
  set "config_active_dir=%config_active_dir%"
  set "config_profile_file=%config_profile_file%"
  set "config_cache_dir=%config_cache_dir%"
  set "config_logs_dir=%config_logs_dir%"
  set "screen_cache_dir=%screen_cache_dir%"
  set "screen_cfg_file=%screen_cfg_file%"
  set "saves_active_dir=%saves_active_dir%"
  set "test_dir=%test_dir%"
  set "tools_dir=%tools_dir%"
  set "dev_dir=%dev_dir%"
  set "state_root_dir=%config_active_dir%"
  set "runtime_root_dir=%config_active_dir%\Runtime"
  set "runtime_ipc_dir=%config_active_dir%\Runtime\IPC"
  if not exist "%config_logs_dir%"   md "%config_logs_dir%"   >nul 2>&1
  if not exist "%config_cache_dir%"  md "%config_cache_dir%"  >nul 2>&1
  if not exist "%runtime_ipc_dir%"   md "%runtime_ipc_dir%"   >nul 2>&1
)

rem --- (Optional) Add unique Tools to PATH --------------------------------
set "PATH_TAG=;%PATH%;"
echo %PATH_TAG% | find /I ";%tools_dir%;" >nul || set "PATH=%PATH%;%tools_dir%"

rem --- show & RCSU return ------------------------------------------------
for /f %%e in ('cmd /k prompt $e^<nul') do set "ESC=%%e"
echo %ESC%[92m[OK]%ESC%[0m Path variable setting completed successfully.
call "%RCSU%" -trace INFO SettingPath "Path variable setting completed successfully."
call "%RCSU%" -return %RCS_S_FLOW% %RCS_D_SYS% %RCS_R_OTHER% 000
exit /b %errorlevel%