:: ─── If PROJECT_ROOT exists, use it. If not, complete it yourself. ──
if defined PROJECT_ROOT (
   set "root_dir=%PROJECT_ROOT%"
) else (
   rem %~dp0 = location of this script (…\Src\Main\)
   rem Expand two levels up to get the "Project Root"
   for %%I in ("%~dp0\..\..\..") do set "root_dir=%%~fI\"
)

::===== Under Assets ====================================================
set "assets_dir=%root_dir%\Assets"
set "assets_docs_dir=%assets_dir%\Docs"
set "assets_images_dir=%assets_dir%\Images"
set "assets_sounds_dir=%assets_dir%\Sounds"
   set "assets_sounds_revelation_dir=%assets_sounds_dir%\RevelationOfGod"
   set "assets_sounds_starfall_dir=%assets_sounds_dir%\StarFallHill"
   set "assets_sounds_fx_dir=%assets_sounds_dir%\_SoundEffect"

::===== Under Src =======================================================
set "src_dir=%root_dir%\Src"
set "src_data_dir=%src_dir%\Data"
   set "src_enemydata_dir=%src_data_dir%\EnemyData"
   set "src_itemdata_dir=%src_data_dir%\ItemData"
   set "src_playerdata_dir=%src_data_dir%\PlayerData"
set "src_main_dir=%src_dir%\Main"
set "src_network_dir=%src_dir%\Network"
set "src_stories_dir=%src_dir%\Stories"
   set "src_scenes_dir=%src_stories_dir%\Scenes"
      set "src_scene_newgame_dir=%src_scenes_dir%\00_NewGame"
      set "src_scene_prologue_dir=%src_scenes_dir%\01_Prologue"
      rem (Other scenes are dynamically referenced by %src_scenes_dir%\{ID_Name})
   set "src_textassets_dir=%src_stories_dir%\TextAssets"
      set "src_text_newgame_dir=%src_textassets_dir%\00_NewGame"
      set "src_text_prologue_dir=%src_textassets_dir%\01_Prologue"
      rem (Also dynamically accessible)

set "src_systems_dir=%src_dir%\Systems"
   set "src_audio_dir=%src_systems_dir%\Audio"
   set "src_bootstrap_dir=%src_systems_dir%\Bootstrap"
   set "src_debug_dir=%src_systems_dir%\Debug"
   set "src_display_dir=%src_systems_dir%\Display"
      set "src_display_mod_dir=%src_display_dir%\Modules"
      set "src_display_tpl_dir=%src_display_dir%\Templates"
   set "src_env_dir=%src_systems_dir%\Environment"
   set "src_launcher_dir=%src_systems_dir%\Launcher"
   set "src_savesys_dir=%src_systems_dir%\SaveSys"

::===== Config (active location resolved by SAVE_MODE / CFG_DIR) ========
set "config_root_dir=%root_dir%\Config"

if defined CFG_DIR (
   rem Run.bat等から明示された場所を最優先
   set "config_active_dir=%CFG_DIR%"
) else (
   if /i "%SAVE_MODE%"=="localappdata" (
      set "config_active_dir=%LOCALAPPDATA%\HedgeHogSoft\AstralDivide\Config"
   ) else if /i "%SAVE_MODE%"=="custom" (
      if defined SAVE_DIR (
         set "config_active_dir=%SAVE_DIR%\_config"
      ) else (
         set "config_active_dir=%config_root_dir%"
      )
   ) else (
      rem default: portable
      set "config_active_dir=%config_root_dir%"
   )
)

set "config_profile_file=%config_active_dir%\profile.env"
set "config_cache_dir=%config_active_dir%\Cache"
set "config_logs_dir=%config_active_dir%\Logs"

rem --- Screen env cache (generated by ScreenEnvironmentDetection.bat) ---
set "screen_cache_dir=%config_cache_dir%\Screen\%COMPUTERNAME%"
set "screen_cfg_file=%screen_cache_dir%\screen_config.env"

::===== Saves (active) ==================================================
if defined SAVE_DIR (
   set "saves_active_dir=%SAVE_DIR%"
) else (
   set "saves_active_dir=%root_dir%\Saves"
)

::===== Test / Tools / [DEV] ===========================================
set "test_dir=%root_dir%\Test"
set "tools_dir=%root_dir%\Tools"
set "dev_dir=%root_dir%\[DEV]"

rem //===== Verification output (for debug) =============================
rem //echo root_dir                = %root_dir%
rem //echo config_active_dir       = %config_active_dir%
rem //echo config_profile_file     = %config_profile_file%
rem //echo screen_cfg_file         = %screen_cfg_file%
rem //echo saves_active_dir        = %saves_active_dir%
rem //echo src_main_dir            = %src_main_dir%
rem //echo tools_dir               = %tools_dir%
rem //timeout /t 1

::===== Notice ==========================================================
:: This configuration is resilient to structural changes:
::  - Change only the *root* vars (assets_dir / config_root_dir etc.) and children follow.
::  - Config is redirected by SAVE_MODE/CFG_DIR for portable/localappdata/custom.

echo %esc%[92m[OK]%esc%[0m Path variable setting completed successfully.
timeout /t 1 > nul
