@echo off
set "NODE_Town03_MarketStreet_A=move:Town13_MeteorShop"
set "NODE_Town03_MarketStreet_A_LABEL=店並みへ向く"

set "NODE_Town13_MeteorShop_BG=Chapter01_Town_13_MeteorShop.png"
set "NODE_Town13_MeteorShop_LOCATION=王都エリュシオン - 商店街"
set "NODE_Town13_MeteorShop_TITLE=流星の雫薬舗"
set "NODE_Town13_MeteorShop_DESC1=青い星印の布が揺れる薬舗。店主ノーラがこちらに気づいて微笑んだ。"
set "NODE_Town13_MeteorShop_DESC2=薬瓶と乾燥薬草が整然と並び、馴染み客にも扱いやすい空気がある。"
set "NODE_Town13_MeteorShop_W=text:天幕越しに柔らかな昼の光が差し込んでいる。"
set "NODE_Town13_MeteorShop_A=text:これ以上左には別の店は見えない。"
set "NODE_Town13_MeteorShop_S=move:Town03_MarketStreet"
set "NODE_Town13_MeteorShop_D=move:Town14_ArdenSmith"
set "NODE_Town13_MeteorShop_E=shop:MeteorShop"
set "NODE_Town13_MeteorShop_W_LABEL=空を見上げる"
set "NODE_Town13_MeteorShop_A_LABEL=左端を確かめる"
set "NODE_Town13_MeteorShop_S_LABEL=通りへ戻る"
set "NODE_Town13_MeteorShop_D_LABEL=隣の武具店を見る"
set "NODE_Town13_MeteorShop_E_LABEL=ノーラに声をかける"

set "NODE_Town14_ArdenSmith_BG=Chapter01_Town_14_ArdenSmith.png"
set "NODE_Town14_ArdenSmith_LOCATION=王都エリュシオン - 商店街"
set "NODE_Town14_ArdenSmith_TITLE=アルデン武具店"
set "NODE_Town14_ArdenSmith_DESC1=年季の入った武具店。アルデンが手を止め、いつもの調子で迎えてくれる。"
set "NODE_Town14_ArdenSmith_DESC2=槍や胸当てが整然と吊られ、通い慣れた安心感のある店先だ。"
set "NODE_Town14_ArdenSmith_W=text:看板の金具が陽を返し、磨かれた刃が鈍く光る。"
set "NODE_Town14_ArdenSmith_A=move:Town13_MeteorShop"
set "NODE_Town14_ArdenSmith_S=move:Town03_MarketStreet"
set "NODE_Town14_ArdenSmith_D=move:Town15_HolyRingWorkshop"
set "NODE_Town14_ArdenSmith_E=shop:ArdenSmith"
set "NODE_Town14_ArdenSmith_W_LABEL=武具棚を見る"
set "NODE_Town14_ArdenSmith_A_LABEL=薬舗へ戻る"
set "NODE_Town14_ArdenSmith_S_LABEL=通りへ戻る"
set "NODE_Town14_ArdenSmith_D_LABEL=角の工房を見る"
set "NODE_Town14_ArdenSmith_E_LABEL=アルデンに声をかける"

set "NODE_Town15_HolyRingWorkshop_BG=Chapter01_Town_15_HolyRingWorkshop.png"
set "NODE_Town15_HolyRingWorkshop_LOCATION=王都エリュシオン - 商店街"
set "NODE_Town15_HolyRingWorkshop_TITLE=聖環工房"
set "NODE_Town15_HolyRingWorkshop_DESC1=聖具と装飾品を扱う工房。祝祭準備のため店主は不在らしい。"
set "NODE_Town15_HolyRingWorkshop_DESC2=値札付きの品は見られるが、今日は注文も購入も受け付けていない。"
set "NODE_Town15_HolyRingWorkshop_W=text:店内の硝子ケースには細工の細かな聖具が並んでいる。"
set "NODE_Town15_HolyRingWorkshop_A=move:Town14_ArdenSmith"
set "NODE_Town15_HolyRingWorkshop_S=move:Town03_MarketStreet"
set "NODE_Town15_HolyRingWorkshop_D=text:ここが店並みの角で、その先は横道へ抜けている。"
set "NODE_Town15_HolyRingWorkshop_E=shop:HolyRingWorkshop"
set "NODE_Town15_HolyRingWorkshop_W_LABEL=聖具棚を見る"
set "NODE_Town15_HolyRingWorkshop_A_LABEL=武具店へ戻る"
set "NODE_Town15_HolyRingWorkshop_S_LABEL=通りへ戻る"
set "NODE_Town15_HolyRingWorkshop_D_LABEL=角を確かめる"
set "NODE_Town15_HolyRingWorkshop_E_LABEL=店先を覗く"
exit /b 0
